version: '3'

vars:
  BLOG_DIR: $BR2/Personal/Blog

tasks:
  pub:
    desc: "Publish to github by committing a new version of the website"
    cmds:
      - git add .
      - git commit -m "Release from script"
      - git push
    


